from setuptools import setup, find_packages

setup(
    name='smart_nexus',
    version='0.0.1',
    packages=find_packages(),
    install_requires=[
        "fastapi",
        "uvicorn",
        "python-dotenv",
        "pydantic",
        "pydantic-settings",
        "openai",
        "openai-agents",
        "pymysql",
        "dbutils",
        "pystun3",
        "python-multipart",
        "aiofiles",
        "beautifulsoup4",
        "tqdm",
        "langchain-text-splitters",
        "langchain-classic",
        "requests",
        "langchain-core",
        "langchain-community",
        "langchain-openai",
        "langchain-chroma",
        "markdownify",
        "scikit-learn",
        "jieba",
        "unstructured",
        "markdown"
    ]
)