events {}

http {
    # 从 X-Forwarded-For 提取第一个 IP（即用户真实公网 IP）
    map $http_x_forwarded_for $client_real_ip {
        default                       $remote_addr;
        "~^(?P<firstip>[^,]+)"        $firstip;
    }

    # ===== knowledge 知识库服务组 =====
    upstream knowledge {
        server knowledge:8000;  # 容器之间通过服务名通信
    }

    # ===== consultant 顾问服务组 =====
    upstream consultant {
        server consultant:8001; # 容器之间通过服务名通信
    }

    # HTTP 自动跳转 HTTPS
#      server {
#          listen 80;
#          server_name www.apidev-app.com;
#          return 301 https://$host$request_uri;
#      }

    server {
        # http环境下使用，走 公网ip->127.0.0.1
	    listen 80;

        # https环境下使用
#          listen 443 ssl;
#          server_name www.apidev-app.com;
#
#          ssl_certificate     /etc/nginx/ssl/fullchain.pem;
#          ssl_certificate_key /etc/nginx/ssl/privkey.pem;

        # consultant
        location /smart/nexus/consultant {
            proxy_pass http://consultant; # 将请求转发到 consultant 服务组
            proxy_http_version 1.1;

            # SSE 关键配置 ↓
            proxy_buffering off; # 禁用代理缓冲，确保SSE数据实时传输
            proxy_cache off; # 禁用缓存，确保SSE实时数据传输
            proxy_set_header Connection ''; # 清除 Connection 头，防止 nginx 关闭连接
            chunked_transfer_encoding on; # 启用分块传输编码，适用于 SSE 长连接
            proxy_read_timeout 300s;   # SSE 长连接超时时间

            # 标准代理头
            proxy_set_header Host $host; # 获取前端http头请求过来的域名/ip，确保后端服务正确识别发起请求的域名/ip
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 将客户端 IP 添加到 X-Forwarded-For 头中，确保后端服务能够获取到用户真实公网 IP
            proxy_set_header X-Real-IP $remote_addr; # 从TCP连接中获取源 IP 地址，传递客户端真实IP到后端
        }

        # knowledge
        location /smart/nexus/knowledge {
            proxy_pass http://knowledge; # 将请求转发到 knowledge 服务组
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

